seed: 42
batch_size: 1
epochs: 15
lr: 0.001
lr_gamma: 0.2
lr_step_size: 10
acum_step: 8
run: 7
accelerator: auto
limit_train_batches: null
limit_val_batches: null
num_sanity_val_steps: 0
checkpoint_dir: experiments/logs
checkpoint_monitor: ssim
checkpoint_mode: max
checkpoint_save_top_k: 1
checkpoint_save_last: true
